/**
 * Generated by pnpm ai:presets:update from https://models.dev/api.json.
 * Source: sst/models.dev (MIT); see docs/licenses/models.dev-MIT.md.
 */

export const API_PRESET_SNAPSHOT = {
  "source": "https://models.dev/api.json",
  "generatedAt": "2026-07-24T21:01:09.013Z",
  "presets": [
    {
      "id": "models-dev:302ai",
      "name": "302.AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.302.ai/v1",
      "docsUrl": "https://doc.302.ai",
      "logoId": "302ai"
    },
    {
      "id": "models-dev:abacus",
      "name": "Abacus",
      "protocol": "openai-compatible",
      "baseUrl": "https://routellm.abacus.ai/v1",
      "docsUrl": "https://abacus.ai/help/api",
      "logoId": "abacus"
    },
    {
      "id": "models-dev:abliteration-ai",
      "name": "abliteration.ai",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.abliteration.ai/v1",
      "docsUrl": "https://docs.abliteration.ai/models",
      "logoId": "abliteration-ai"
    },
    {
      "id": "models-dev:ai-router",
      "name": "AI-ROUTER",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.ai-router.dev/v1",
      "docsUrl": "https://ai-router.dev/openai-compatible-api-gateway/",
      "logoId": "ai-router"
    },
    {
      "id": "models-dev:aiand",
      "name": "ai&",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.aiand.com/v1",
      "docsUrl": "https://docs.aiand.com/",
      "logoId": "aiand"
    },
    {
      "id": "models-dev:aki-io",
      "name": "AKI.IO",
      "protocol": "openai-compatible",
      "baseUrl": "https://aki.io/v1",
      "docsUrl": "https://aki.io/docs/",
      "logoId": "aki-io"
    },
    {
      "id": "models-dev:alibaba",
      "name": "Alibaba",
      "protocol": "openai-compatible",
      "baseUrl": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
      "docsUrl": "https://www.alibabacloud.com/help/en/model-studio/models",
      "logoId": "alibaba"
    },
    {
      "id": "models-dev:alibaba-cn",
      "name": "Alibaba (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
      "docsUrl": "https://www.alibabacloud.com/help/en/model-studio/models",
      "logoId": "alibaba-cn"
    },
    {
      "id": "models-dev:alibaba-coding-plan",
      "name": "Alibaba Coding Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://coding-intl.dashscope.aliyuncs.com/v1",
      "docsUrl": "https://www.alibabacloud.com/help/en/model-studio/coding-plan",
      "logoId": "alibaba-coding-plan"
    },
    {
      "id": "models-dev:alibaba-coding-plan-cn",
      "name": "Alibaba Coding Plan (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://coding.dashscope.aliyuncs.com/v1",
      "docsUrl": "https://help.aliyun.com/zh/model-studio/coding-plan",
      "logoId": "alibaba-coding-plan-cn"
    },
    {
      "id": "models-dev:alibaba-token-plan",
      "name": "Alibaba Token Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
      "docsUrl": "https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",
      "logoId": "alibaba-token-plan"
    },
    {
      "id": "models-dev:alibaba-token-plan-cn",
      "name": "Alibaba Token Plan (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
      "docsUrl": "https://www.alibabacloud.com/help/zh/model-studio/token-plan-overview",
      "logoId": "alibaba-token-plan-cn"
    },
    {
      "id": "models-dev:ambient",
      "name": "Ambient",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.ambient.xyz/v1",
      "docsUrl": "https://ambient.xyz",
      "logoId": "ambient"
    },
    {
      "id": "models-dev:anthropic",
      "name": "Anthropic",
      "protocol": "anthropic",
      "baseUrl": "https://api.anthropic.com/v1",
      "docsUrl": "https://docs.anthropic.com/en/docs/about-claude/models",
      "logoId": "anthropic"
    },
    {
      "id": "models-dev:anyapi",
      "name": "AnyAPI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.anyapi.ai/v1",
      "docsUrl": "https://docs.anyapi.ai",
      "logoId": "anyapi"
    },
    {
      "id": "models-dev:atomic-chat",
      "name": "Atomic Chat",
      "protocol": "openai-compatible",
      "baseUrl": "http://127.0.0.1:1337/v1",
      "docsUrl": "https://atomic.chat",
      "logoId": "atomic-chat"
    },
    {
      "id": "models-dev:auriko",
      "name": "Auriko",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.auriko.ai/v1",
      "docsUrl": "https://docs.auriko.ai",
      "logoId": "auriko"
    },
    {
      "id": "models-dev:bailing",
      "name": "Bailing",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.tbox.cn/api/llm/v1/chat/completions",
      "docsUrl": "https://alipaytbox.yuque.com/sxs0ba/ling/intro",
      "logoId": "bailing"
    },
    {
      "id": "models-dev:baseten",
      "name": "Baseten",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.baseten.co/v1",
      "docsUrl": "https://docs.baseten.co/inference/model-apis/overview",
      "logoId": "baseten"
    },
    {
      "id": "models-dev:berget",
      "name": "Berget.AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.berget.ai/v1",
      "docsUrl": "https://api.berget.ai",
      "logoId": "berget"
    },
    {
      "id": "models-dev:blueclaw",
      "name": "Blue Claw",
      "protocol": "openai-compatible",
      "baseUrl": "https://openai.blueclaw.network/v1",
      "docsUrl": "https://blueclaw.network",
      "logoId": "blueclaw"
    },
    {
      "id": "models-dev:chutes",
      "name": "Chutes",
      "protocol": "openai-compatible",
      "baseUrl": "https://llm.chutes.ai/v1",
      "docsUrl": "https://llm.chutes.ai/v1/models",
      "logoId": "chutes"
    },
    {
      "id": "models-dev:clarifai",
      "name": "Clarifai",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.clarifai.com/v2/ext/openai/v1",
      "docsUrl": "https://docs.clarifai.com/compute/inference/",
      "logoId": "clarifai"
    },
    {
      "id": "models-dev:claudinio",
      "name": "Claudinio",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.claudin.io/v1",
      "docsUrl": "https://claudin.io",
      "logoId": "claudinio"
    },
    {
      "id": "models-dev:cline-pass",
      "name": "ClinePass",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.cline.bot/api/v1",
      "docsUrl": "https://docs.cline.bot/getting-started/clinepass",
      "logoId": "cline-pass"
    },
    {
      "id": "models-dev:cloudferro-sherlock",
      "name": "CloudFerro Sherlock",
      "protocol": "openai-compatible",
      "baseUrl": "https://api-sherlock.cloudferro.com/openai/v1/",
      "docsUrl": "https://docs.sherlock.cloudferro.com/",
      "logoId": "cloudferro-sherlock"
    },
    {
      "id": "models-dev:cloudflare-workers-ai",
      "name": "Cloudflare Workers AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1",
      "docsUrl": "https://developers.cloudflare.com/workers-ai/models/",
      "logoId": "cloudflare-workers-ai"
    },
    {
      "id": "models-dev:cortecs",
      "name": "Cortecs",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.cortecs.ai/v1",
      "docsUrl": "https://api.cortecs.ai/v1/models",
      "logoId": "cortecs"
    },
    {
      "id": "models-dev:crof",
      "name": "CrofAI",
      "protocol": "openai-compatible",
      "baseUrl": "https://crof.ai/v1",
      "docsUrl": "https://crof.ai/docs",
      "logoId": "crof"
    },
    {
      "id": "models-dev:crossmodel",
      "name": "CrossModel",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.crossmodel.ai/v1",
      "docsUrl": "https://www.crossmodel.ai/docs",
      "logoId": "crossmodel"
    },
    {
      "id": "models-dev:drun",
      "name": "D.Run (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://chat.d.run/v1",
      "docsUrl": "https://www.d.run",
      "logoId": "drun"
    },
    {
      "id": "models-dev:daoxe",
      "name": "DaoXE",
      "protocol": "openai-compatible",
      "baseUrl": "https://daoxe.com/v1",
      "docsUrl": "https://daoxe.com/pricing",
      "logoId": "daoxe"
    },
    {
      "id": "models-dev:databricks",
      "name": "Databricks",
      "protocol": "openai-compatible",
      "baseUrl": "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1",
      "docsUrl": "https://docs.databricks.com/aws/en/machine-learning/foundation-models/",
      "logoId": "databricks"
    },
    {
      "id": "models-dev:deepseek",
      "name": "DeepSeek",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.deepseek.com",
      "docsUrl": "https://api-docs.deepseek.com/quick_start/pricing",
      "logoId": "deepseek"
    },
    {
      "id": "models-dev:digitalocean",
      "name": "DigitalOcean",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.do-ai.run/v1",
      "docsUrl": "https://docs.digitalocean.com/products/gradient-ai-platform/details/models/",
      "logoId": "digitalocean"
    },
    {
      "id": "models-dev:dinference",
      "name": "DInference",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.dinference.com/v1",
      "docsUrl": "https://dinference.com",
      "logoId": "dinference"
    },
    {
      "id": "models-dev:ebcloud",
      "name": "EBCloud",
      "protocol": "openai-compatible",
      "baseUrl": "https://maas-api.ebcloud.com/v1",
      "docsUrl": "https://docs.ebtech.com/ai/model-api.html",
      "logoId": "ebcloud"
    },
    {
      "id": "models-dev:empiriolabs",
      "name": "EmpirioLabs AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.empiriolabs.ai/v1",
      "docsUrl": "https://docs.empiriolabs.ai",
      "logoId": "empiriolabs"
    },
    {
      "id": "models-dev:evroc",
      "name": "evroc",
      "protocol": "openai-compatible",
      "baseUrl": "https://models.think.evroc.com/v1",
      "docsUrl": "https://docs.evroc.com/products/think/overview.html",
      "logoId": "evroc"
    },
    {
      "id": "models-dev:fastrouter",
      "name": "FastRouter",
      "protocol": "openai-compatible",
      "baseUrl": "https://go.fastrouter.ai/api/v1",
      "docsUrl": "https://fastrouter.ai/models",
      "logoId": "fastrouter"
    },
    {
      "id": "models-dev:fireworks-ai",
      "name": "Fireworks AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.fireworks.ai/inference/v1/",
      "docsUrl": "https://fireworks.ai/docs/",
      "logoId": "fireworks-ai"
    },
    {
      "id": "models-dev:freemodel",
      "name": "FreeModel",
      "protocol": "anthropic",
      "baseUrl": "https://cc.freemodel.dev/v1",
      "docsUrl": "https://freemodel.dev",
      "logoId": "freemodel"
    },
    {
      "id": "models-dev:friendli",
      "name": "Friendli",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.friendli.ai/serverless/v1",
      "docsUrl": "https://friendli.ai/docs/guides/serverless_endpoints/introduction",
      "logoId": "friendli"
    },
    {
      "id": "models-dev:frogbot",
      "name": "FrogBot",
      "protocol": "openai-compatible",
      "baseUrl": "https://app.frogbot.ai/api/v1",
      "docsUrl": "https://docs.frogbot.ai",
      "logoId": "frogbot"
    },
    {
      "id": "models-dev:github-copilot",
      "name": "GitHub Copilot",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.githubcopilot.com",
      "docsUrl": "https://docs.github.com/en/copilot",
      "logoId": "github-copilot"
    },
    {
      "id": "models-dev:github-models",
      "name": "GitHub Models",
      "protocol": "openai-compatible",
      "baseUrl": "https://models.github.ai/inference",
      "docsUrl": "https://docs.github.com/en/github-models",
      "logoId": "github-models"
    },
    {
      "id": "models-dev:gmicloud",
      "name": "GMI Cloud",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.gmi-serving.com/v1",
      "docsUrl": "https://docs.gmicloud.ai/inference-engine/api-reference/llm-api-reference",
      "logoId": "gmicloud"
    },
    {
      "id": "models-dev:google",
      "name": "Google",
      "protocol": "google",
      "baseUrl": "https://generativelanguage.googleapis.com/v1beta",
      "docsUrl": "https://ai.google.dev/gemini-api/docs/models",
      "logoId": "google"
    },
    {
      "id": "models-dev:helicone",
      "name": "Helicone",
      "protocol": "openai-compatible",
      "baseUrl": "https://ai-gateway.helicone.ai/v1",
      "docsUrl": "https://helicone.ai/models",
      "logoId": "helicone"
    },
    {
      "id": "models-dev:hetzner",
      "name": "Hetzner",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.hetzner.com/api/v1",
      "docsUrl": "https://experiments.hetzner.com/docs/inference",
      "logoId": "hetzner"
    },
    {
      "id": "models-dev:hpc-ai",
      "name": "HPC-AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.hpc-ai.com/inference/v1",
      "docsUrl": "https://www.hpc-ai.com/doc/docs/quickstart/",
      "logoId": "hpc-ai"
    },
    {
      "id": "models-dev:huggingface",
      "name": "Hugging Face",
      "protocol": "openai-compatible",
      "baseUrl": "https://router.huggingface.co/v1",
      "docsUrl": "https://huggingface.co/docs/inference-providers",
      "logoId": "huggingface"
    },
    {
      "id": "models-dev:iflowcn",
      "name": "iFlow",
      "protocol": "openai-compatible",
      "baseUrl": "https://apis.iflow.cn/v1",
      "docsUrl": "https://platform.iflow.cn/en/docs",
      "logoId": "iflowcn"
    },
    {
      "id": "models-dev:inception",
      "name": "Inception",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.inceptionlabs.ai/v1/",
      "docsUrl": "https://platform.inceptionlabs.ai/docs",
      "logoId": "inception"
    },
    {
      "id": "models-dev:inceptron",
      "name": "Inceptron",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.inceptron.io/v1",
      "docsUrl": "https://docs.inceptron.io",
      "logoId": "inceptron"
    },
    {
      "id": "models-dev:inference",
      "name": "Inference",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.net/v1",
      "docsUrl": "https://inference.net/models",
      "logoId": "inference"
    },
    {
      "id": "models-dev:inferx",
      "name": "InferX",
      "protocol": "openai-compatible",
      "baseUrl": "https://model.inferx.net/endpoints/v1",
      "docsUrl": "https://model.inferx.net/endpoints",
      "logoId": "inferx"
    },
    {
      "id": "models-dev:io-net",
      "name": "IO.NET",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.intelligence.io.solutions/api/v1",
      "docsUrl": "https://io.net/docs/guides/intelligence/io-intelligence",
      "logoId": "io-net"
    },
    {
      "id": "models-dev:jiekou",
      "name": "Jiekou.AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.jiekou.ai/openai",
      "docsUrl": "https://docs.jiekou.ai/docs/support/quickstart?utm_source=github_models.dev",
      "logoId": "jiekou"
    },
    {
      "id": "models-dev:kenari",
      "name": "Kenari",
      "protocol": "openai-compatible",
      "baseUrl": "https://kenari.id/v1",
      "docsUrl": "https://kenari.id/docs",
      "logoId": "kenari"
    },
    {
      "id": "models-dev:kilo",
      "name": "Kilo Gateway",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.kilo.ai/api/gateway",
      "docsUrl": "https://kilo.ai",
      "logoId": "kilo"
    },
    {
      "id": "models-dev:kimi-for-coding",
      "name": "Kimi For Coding",
      "protocol": "anthropic",
      "baseUrl": "https://api.kimi.com/coding/v1",
      "docsUrl": "https://www.kimi.com/code/docs/en/third-party-tools/other-coding-agents.html",
      "logoId": "kimi-for-coding"
    },
    {
      "id": "models-dev:kuae-cloud-coding-plan",
      "name": "KUAE Cloud Coding Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://coding-plan-endpoint.kuaecloud.net/v1",
      "docsUrl": "https://docs.mthreads.com/kuaecloud/kuaecloud-doc-online/coding_plan/",
      "logoId": "kuae-cloud-coding-plan"
    },
    {
      "id": "models-dev:lilac",
      "name": "Lilac",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.getlilac.com/v1",
      "docsUrl": "https://docs.getlilac.com/inference/models",
      "logoId": "lilac"
    },
    {
      "id": "models-dev:llama",
      "name": "Llama",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.llama.com/compat/v1/",
      "docsUrl": "https://llama.developer.meta.com/docs/models",
      "logoId": "llama"
    },
    {
      "id": "models-dev:llmgateway",
      "name": "LLM Gateway",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.llmgateway.io/v1",
      "docsUrl": "https://llmgateway.io/docs",
      "logoId": "llmgateway"
    },
    {
      "id": "models-dev:llmtr",
      "name": "LLMTR",
      "protocol": "openai-compatible",
      "baseUrl": "https://llmtr.com/v1",
      "docsUrl": "https://llmtr.com/docs",
      "logoId": "llmtr"
    },
    {
      "id": "models-dev:lmstudio",
      "name": "LMStudio",
      "protocol": "openai-compatible",
      "baseUrl": "http://127.0.0.1:1234/v1",
      "docsUrl": "https://lmstudio.ai/models",
      "logoId": "lmstudio"
    },
    {
      "id": "models-dev:longcat",
      "name": "LongCat",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.longcat.chat/openai",
      "docsUrl": "https://longcat.chat/platform/docs/",
      "logoId": "longcat"
    },
    {
      "id": "models-dev:lucidquery",
      "name": "LucidQuery",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.lucidquery.com/v1",
      "docsUrl": "https://lucidquery.com/docs",
      "logoId": "lucidquery"
    },
    {
      "id": "models-dev:lynkr",
      "name": "Lynkr",
      "protocol": "openai-compatible",
      "baseUrl": "http://127.0.0.1:8081/v1",
      "docsUrl": "https://github.com/Fast-Editor/Lynkr",
      "logoId": "lynkr"
    },
    {
      "id": "models-dev:meganova",
      "name": "Meganova",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.meganova.ai/v1",
      "docsUrl": "https://docs.meganova.ai",
      "logoId": "meganova"
    },
    {
      "id": "models-dev:meta",
      "name": "Meta",
      "protocol": "openai",
      "baseUrl": "https://api.meta.ai/v1",
      "docsUrl": "https://dev.meta.ai/docs",
      "logoId": "meta"
    },
    {
      "id": "models-dev:minimax",
      "name": "MiniMax (minimax.io)",
      "protocol": "anthropic",
      "baseUrl": "https://api.minimax.io/anthropic/v1",
      "docsUrl": "https://platform.minimax.io/docs/guides/quickstart",
      "logoId": "minimax"
    },
    {
      "id": "models-dev:minimax-cn",
      "name": "MiniMax (minimaxi.com)",
      "protocol": "anthropic",
      "baseUrl": "https://api.minimaxi.com/anthropic/v1",
      "docsUrl": "https://platform.minimaxi.com/docs/guides/quickstart",
      "logoId": "minimax-cn"
    },
    {
      "id": "models-dev:minimax-coding-plan",
      "name": "MiniMax Token Plan (minimax.io)",
      "protocol": "anthropic",
      "baseUrl": "https://api.minimax.io/anthropic/v1",
      "docsUrl": "https://platform.minimax.io/docs/token-plan/intro",
      "logoId": "minimax-coding-plan"
    },
    {
      "id": "models-dev:minimax-cn-coding-plan",
      "name": "MiniMax Token Plan (minimaxi.com)",
      "protocol": "anthropic",
      "baseUrl": "https://api.minimaxi.com/anthropic/v1",
      "docsUrl": "https://platform.minimaxi.com/docs/token-plan/intro",
      "logoId": "minimax-cn-coding-plan"
    },
    {
      "id": "models-dev:mixlayer",
      "name": "Mixlayer",
      "protocol": "openai-compatible",
      "baseUrl": "https://models.mixlayer.ai/v1",
      "docsUrl": "https://docs.mixlayer.com",
      "logoId": "mixlayer"
    },
    {
      "id": "models-dev:moark",
      "name": "Moark",
      "protocol": "openai-compatible",
      "baseUrl": "https://moark.com/v1",
      "docsUrl": "https://moark.com/docs/openapi/v1#tag/%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90",
      "logoId": "moark"
    },
    {
      "id": "models-dev:model-oracle-ai",
      "name": "Model Oracle AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.modeloracle.com/api/v1",
      "docsUrl": "https://modeloracle.com/setup/",
      "logoId": "model-oracle-ai"
    },
    {
      "id": "models-dev:modelscope",
      "name": "ModelScope",
      "protocol": "openai-compatible",
      "baseUrl": "https://api-inference.modelscope.cn/v1",
      "docsUrl": "https://modelscope.cn/docs/model-service/API-Inference/intro",
      "logoId": "modelscope"
    },
    {
      "id": "models-dev:moonshotai",
      "name": "Moonshot AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.moonshot.ai/v1",
      "docsUrl": "https://platform.moonshot.ai/docs/api/chat",
      "logoId": "moonshotai"
    },
    {
      "id": "models-dev:moonshotai-cn",
      "name": "Moonshot AI (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.moonshot.cn/v1",
      "docsUrl": "https://platform.moonshot.cn/docs/api/chat",
      "logoId": "moonshotai-cn"
    },
    {
      "id": "models-dev:morph",
      "name": "Morph",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.morphllm.com/v1",
      "docsUrl": "https://docs.morphllm.com/api-reference/introduction",
      "logoId": "morph"
    },
    {
      "id": "models-dev:nano-gpt",
      "name": "NanoGPT",
      "protocol": "openai-compatible",
      "baseUrl": "https://nano-gpt.com/api/v1",
      "docsUrl": "https://docs.nano-gpt.com",
      "logoId": "nano-gpt"
    },
    {
      "id": "models-dev:nearai",
      "name": "NEAR AI Cloud",
      "protocol": "openai-compatible",
      "baseUrl": "https://cloud-api.near.ai/v1",
      "docsUrl": "https://docs.near.ai/",
      "logoId": "nearai"
    },
    {
      "id": "models-dev:nebius",
      "name": "Nebius Token Factory",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.tokenfactory.nebius.com/v1",
      "docsUrl": "https://docs.tokenfactory.nebius.com/",
      "logoId": "nebius"
    },
    {
      "id": "models-dev:neon",
      "name": "Neon",
      "protocol": "openai-compatible",
      "baseUrl": "${NEON_AI_GATEWAY_BASE_URL}/v1",
      "docsUrl": "https://neon.com/docs",
      "logoId": "neon"
    },
    {
      "id": "models-dev:neuralwatt",
      "name": "Neuralwatt",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.neuralwatt.com/v1",
      "docsUrl": "https://portal.neuralwatt.com/docs",
      "logoId": "neuralwatt"
    },
    {
      "id": "models-dev:nova",
      "name": "Nova",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.nova.amazon.com/v1",
      "docsUrl": "https://nova.amazon.com/dev/documentation",
      "logoId": "nova"
    },
    {
      "id": "models-dev:novita-ai",
      "name": "NovitaAI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.novita.ai/openai",
      "docsUrl": "https://novita.ai/docs/guides/introduction",
      "logoId": "novita-ai"
    },
    {
      "id": "models-dev:nvidia",
      "name": "Nvidia",
      "protocol": "openai-compatible",
      "baseUrl": "https://integrate.api.nvidia.com/v1",
      "docsUrl": "https://docs.api.nvidia.com/nim/",
      "logoId": "nvidia"
    },
    {
      "id": "models-dev:ofox",
      "name": "Ofox",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.ofox.ai/v1",
      "docsUrl": "https://ofox.ai/docs",
      "logoId": "ofox"
    },
    {
      "id": "models-dev:ollama-cloud",
      "name": "Ollama Cloud",
      "protocol": "openai-compatible",
      "baseUrl": "https://ollama.com/v1",
      "docsUrl": "https://docs.ollama.com/cloud",
      "logoId": "ollama-cloud"
    },
    {
      "id": "models-dev:openai",
      "name": "OpenAI",
      "protocol": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "docsUrl": "https://platform.openai.com/docs/models",
      "logoId": "openai"
    },
    {
      "id": "models-dev:opencode-go",
      "name": "OpenCode Go",
      "protocol": "openai-compatible",
      "baseUrl": "https://opencode.ai/zen/go/v1",
      "docsUrl": "https://opencode.ai/docs/zen",
      "logoId": "opencode-go"
    },
    {
      "id": "models-dev:opencode",
      "name": "OpenCode Zen",
      "protocol": "openai-compatible",
      "baseUrl": "https://opencode.ai/zen/v1",
      "docsUrl": "https://opencode.ai/docs/zen",
      "logoId": "opencode"
    },
    {
      "id": "models-dev:orcarouter",
      "name": "OrcaRouter",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.orcarouter.ai/v1",
      "docsUrl": "https://docs.orcarouter.ai",
      "logoId": "orcarouter"
    },
    {
      "id": "models-dev:ovhcloud",
      "name": "OVHcloud AI Endpoints",
      "protocol": "openai-compatible",
      "baseUrl": "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
      "docsUrl": "https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog//",
      "logoId": "ovhcloud"
    },
    {
      "id": "models-dev:perplexity-agent",
      "name": "Perplexity Agent",
      "protocol": "openai",
      "baseUrl": "https://api.perplexity.ai/v1",
      "docsUrl": "https://docs.perplexity.ai/docs/agent-api/models",
      "logoId": "perplexity-agent"
    },
    {
      "id": "models-dev:pioneer",
      "name": "Pioneer",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.pioneer.ai/v1",
      "docsUrl": "https://agent.pioneer.ai/llms.txt",
      "logoId": "pioneer"
    },
    {
      "id": "models-dev:poe",
      "name": "Poe",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.poe.com/v1",
      "docsUrl": "https://creator.poe.com/docs/external-applications/openai-compatible-api",
      "logoId": "poe"
    },
    {
      "id": "models-dev:poolside",
      "name": "Poolside",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.poolside.ai/v1",
      "docsUrl": "https://platform.poolside.ai",
      "logoId": "poolside"
    },
    {
      "id": "models-dev:privatemode-ai",
      "name": "Privatemode AI",
      "protocol": "openai-compatible",
      "baseUrl": "http://localhost:8080/v1",
      "docsUrl": "https://docs.privatemode.ai/api/overview",
      "logoId": "privatemode-ai"
    },
    {
      "id": "models-dev:qihang-ai",
      "name": "QiHang",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.qhaigc.net/v1",
      "docsUrl": "https://www.qhaigc.net/docs",
      "logoId": "qihang-ai"
    },
    {
      "id": "models-dev:qiniu-ai",
      "name": "Qiniu",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.qnaigc.com/v1",
      "docsUrl": "https://developer.qiniu.com/aitokenapi",
      "logoId": "qiniu-ai"
    },
    {
      "id": "models-dev:regolo-ai",
      "name": "Regolo AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.regolo.ai/v1",
      "docsUrl": "https://docs.regolo.ai/",
      "logoId": "regolo-ai"
    },
    {
      "id": "models-dev:requesty",
      "name": "Requesty",
      "protocol": "openai-compatible",
      "baseUrl": "https://router.requesty.ai/v1",
      "docsUrl": "https://requesty.ai/solution/llm-routing/models",
      "logoId": "requesty"
    },
    {
      "id": "models-dev:routing-run",
      "name": "routing.run",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.routing.run/v1",
      "docsUrl": "https://docs.routing.run/api-reference/models",
      "logoId": "routing-run"
    },
    {
      "id": "models-dev:sakana",
      "name": "Sakana AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.sakana.ai/v1",
      "docsUrl": "https://console.sakana.ai/models",
      "logoId": "sakana"
    },
    {
      "id": "models-dev:sarvam",
      "name": "Sarvam AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.sarvam.ai/v1",
      "docsUrl": "https://docs.sarvam.ai/api-reference-docs/getting-started/models",
      "logoId": "sarvam"
    },
    {
      "id": "models-dev:scaleway",
      "name": "Scaleway",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.scaleway.ai/v1",
      "docsUrl": "https://www.scaleway.com/en/docs/generative-apis/",
      "logoId": "scaleway"
    },
    {
      "id": "models-dev:siliconflow",
      "name": "SiliconFlow",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.siliconflow.com/v1",
      "docsUrl": "https://cloud.siliconflow.com/models",
      "logoId": "siliconflow"
    },
    {
      "id": "models-dev:siliconflow-cn",
      "name": "SiliconFlow (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.siliconflow.cn/v1",
      "docsUrl": "https://cloud.siliconflow.com/models",
      "logoId": "siliconflow-cn"
    },
    {
      "id": "models-dev:snowflake-cortex",
      "name": "Snowflake Cortex",
      "protocol": "openai-compatible",
      "baseUrl": "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1",
      "docsUrl": "https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-rest-api",
      "logoId": "snowflake-cortex"
    },
    {
      "id": "models-dev:stackit",
      "name": "STACKIT",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
      "docsUrl": "https://docs.stackit.cloud/products/data-and-ai/ai-model-serving/basics/available-shared-models",
      "logoId": "stackit"
    },
    {
      "id": "models-dev:stepfun",
      "name": "StepFun (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.stepfun.com/v1",
      "docsUrl": "https://platform.stepfun.com/docs/zh/overview/concept",
      "logoId": "stepfun"
    },
    {
      "id": "models-dev:stepfun-ai",
      "name": "StepFun (Global)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.stepfun.ai/v1",
      "docsUrl": "https://platform.stepfun.ai/docs/en/overview/concept",
      "logoId": "stepfun-ai"
    },
    {
      "id": "models-dev:stepfun-step-plan",
      "name": "StepFun Step Plan (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.stepfun.com/step_plan/v1",
      "docsUrl": "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
      "logoId": "stepfun-step-plan"
    },
    {
      "id": "models-dev:stepfun-ai-step-plan",
      "name": "StepFun Step Plan (Global)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.stepfun.ai/step_plan/v1",
      "docsUrl": "https://platform.stepfun.ai/docs/en/step-plan/integrations/reasoning-api",
      "logoId": "stepfun-ai-step-plan"
    },
    {
      "id": "models-dev:subconscious",
      "name": "Subconscious",
      "protocol": "anthropic",
      "baseUrl": "https://api.subconscious.dev/v1",
      "docsUrl": "https://docs.subconscious.dev",
      "logoId": "subconscious"
    },
    {
      "id": "models-dev:submodel",
      "name": "submodel",
      "protocol": "openai-compatible",
      "baseUrl": "https://llm.submodel.ai/v1",
      "docsUrl": "https://submodel.gitbook.io",
      "logoId": "submodel"
    },
    {
      "id": "models-dev:synthetic",
      "name": "Synthetic",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.synthetic.new/openai/v1",
      "docsUrl": "https://synthetic.new/pricing",
      "logoId": "synthetic"
    },
    {
      "id": "models-dev:tencent-coding-plan",
      "name": "Tencent Coding Plan (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.lkeap.cloud.tencent.com/coding/v3",
      "docsUrl": "https://cloud.tencent.com/document/product/1772/128947",
      "logoId": "tencent-coding-plan"
    },
    {
      "id": "models-dev:tencent-token-plan",
      "name": "Tencent Token Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.lkeap.cloud.tencent.com/plan/v3",
      "docsUrl": "https://cloud.tencent.com/document/product/1823/130060",
      "logoId": "tencent-token-plan"
    },
    {
      "id": "models-dev:tencent-tokenhub",
      "name": "Tencent TokenHub",
      "protocol": "openai-compatible",
      "baseUrl": "https://tokenhub.tencentmaas.com/v1",
      "docsUrl": "https://cloud.tencent.com/document/product/1823/130050",
      "logoId": "tencent-tokenhub"
    },
    {
      "id": "models-dev:the-grid-ai",
      "name": "The Grid AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.thegrid.ai/v1",
      "docsUrl": "https://thegrid.ai/docs",
      "logoId": "the-grid-ai"
    },
    {
      "id": "models-dev:thinkingmachines",
      "name": "Thinking Machines",
      "protocol": "anthropic",
      "baseUrl": "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1",
      "docsUrl": "https://tinker-docs.thinkingmachines.ai/tinker/compatible-apis/anthropic/",
      "logoId": "thinkingmachines"
    },
    {
      "id": "models-dev:tinfoil",
      "name": "Tinfoil",
      "protocol": "openai-compatible",
      "baseUrl": "https://inference.tinfoil.sh/v1",
      "docsUrl": "https://docs.tinfoil.sh",
      "logoId": "tinfoil"
    },
    {
      "id": "models-dev:trustedrouter",
      "name": "TrustedRouter",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.trustedrouter.com/v1",
      "docsUrl": "https://trustedrouter.com/docs",
      "logoId": "trustedrouter"
    },
    {
      "id": "models-dev:umans-ai",
      "name": "Umans AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.code.umans.ai/v1",
      "docsUrl": "https://app.umans.ai/offers/code/docs/orgs",
      "logoId": "umans-ai"
    },
    {
      "id": "models-dev:umans-ai-coding-plan",
      "name": "Umans AI Coding Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.code.umans.ai/v1",
      "docsUrl": "https://app.umans.ai/offers/code/docs",
      "logoId": "umans-ai-coding-plan"
    },
    {
      "id": "models-dev:unorouter",
      "name": "UnoRouter",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.unorouter.com/v1",
      "docsUrl": "https://unorouter.com/models",
      "logoId": "unorouter"
    },
    {
      "id": "models-dev:upstage",
      "name": "Upstage",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.upstage.ai/v1/solar",
      "docsUrl": "https://developers.upstage.ai/docs/apis/chat",
      "logoId": "upstage"
    },
    {
      "id": "models-dev:vivgrid",
      "name": "Vivgrid",
      "protocol": "openai",
      "baseUrl": "https://api.vivgrid.com/v1",
      "docsUrl": "https://docs.vivgrid.com/models",
      "logoId": "vivgrid"
    },
    {
      "id": "models-dev:vultr",
      "name": "Vultr",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.vultrinference.com/v1",
      "docsUrl": "https://api.vultrinference.com/",
      "logoId": "vultr"
    },
    {
      "id": "models-dev:wafer.ai",
      "name": "Wafer",
      "protocol": "openai-compatible",
      "baseUrl": "https://pass.wafer.ai/v1",
      "docsUrl": "https://docs.wafer.ai/wafer-pass",
      "logoId": "wafer.ai"
    },
    {
      "id": "models-dev:wandb",
      "name": "Weights & Biases",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.inference.wandb.ai/v1",
      "docsUrl": "https://docs.wandb.ai/guides/integrations/inference/",
      "logoId": "wandb"
    },
    {
      "id": "models-dev:xiaomi",
      "name": "Xiaomi",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.xiaomimimo.com/v1",
      "docsUrl": "https://platform.xiaomimimo.com/#/docs",
      "logoId": "xiaomi"
    },
    {
      "id": "models-dev:xiaomi-token-plan-cn",
      "name": "Xiaomi Token Plan (China)",
      "protocol": "openai-compatible",
      "baseUrl": "https://token-plan-cn.xiaomimimo.com/v1",
      "docsUrl": "https://platform.xiaomimimo.com/#/docs",
      "logoId": "xiaomi-token-plan-cn"
    },
    {
      "id": "models-dev:xiaomi-token-plan-ams",
      "name": "Xiaomi Token Plan (Europe)",
      "protocol": "openai-compatible",
      "baseUrl": "https://token-plan-ams.xiaomimimo.com/v1",
      "docsUrl": "https://platform.xiaomimimo.com/#/docs",
      "logoId": "xiaomi-token-plan-ams"
    },
    {
      "id": "models-dev:xiaomi-token-plan-sgp",
      "name": "Xiaomi Token Plan (Singapore)",
      "protocol": "openai-compatible",
      "baseUrl": "https://token-plan-sgp.xiaomimimo.com/v1",
      "docsUrl": "https://platform.xiaomimimo.com/#/docs",
      "logoId": "xiaomi-token-plan-sgp"
    },
    {
      "id": "models-dev:xpersona",
      "name": "Xpersona",
      "protocol": "openai-compatible",
      "baseUrl": "https://www.xpersona.co/v1",
      "docsUrl": "https://www.xpersona.co/docs",
      "logoId": "xpersona"
    },
    {
      "id": "models-dev:zai",
      "name": "Z.AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.z.ai/api/paas/v4",
      "docsUrl": "https://docs.z.ai/guides/overview/pricing",
      "logoId": "zai"
    },
    {
      "id": "models-dev:zai-coding-plan",
      "name": "Z.AI Coding Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "docsUrl": "https://docs.z.ai/devpack/overview",
      "logoId": "zai-coding-plan"
    },
    {
      "id": "models-dev:zeldoc",
      "name": "Zeldoc",
      "protocol": "openai-compatible",
      "baseUrl": "https://api.zeldoc.ai/v1",
      "docsUrl": "https://docs.zeldoc.ai",
      "logoId": "zeldoc"
    },
    {
      "id": "models-dev:zenifra",
      "name": "Zenifra",
      "protocol": "openai-compatible",
      "baseUrl": "https://ai.zenifra.com/v1",
      "docsUrl": "https://docs.zenifra.com",
      "logoId": "zenifra"
    },
    {
      "id": "models-dev:zenmux",
      "name": "ZenMux",
      "protocol": "openai-compatible",
      "baseUrl": "https://zenmux.ai/api/v1",
      "docsUrl": "https://docs.zenmux.ai",
      "logoId": "zenmux"
    },
    {
      "id": "models-dev:zhipuai",
      "name": "Zhipu AI",
      "protocol": "openai-compatible",
      "baseUrl": "https://open.bigmodel.cn/api/paas/v4",
      "docsUrl": "https://docs.z.ai/guides/overview/pricing",
      "logoId": "zhipuai"
    },
    {
      "id": "models-dev:zhipuai-coding-plan",
      "name": "Zhipu AI Coding Plan",
      "protocol": "openai-compatible",
      "baseUrl": "https://open.bigmodel.cn/api/coding/paas/v4",
      "docsUrl": "https://docs.bigmodel.cn/cn/coding-plan/overview",
      "logoId": "zhipuai-coding-plan"
    },
    {
      "id": "custom-openai-compatible",
      "name": "Custom OpenAI Compatible",
      "protocol": "openai-compatible",
      "baseUrl": "",
      "docsUrl": null,
      "logoId": "openai-compatible"
    }
  ]
} as const;
