/** Explicit release-time updater. Normal runtime and builds never import this file. */

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const SOURCE_URL = "https://models.dev/api.json";
const OUTPUT = resolve("packages/ai-runtime/src/api-presets.generated.ts");

type Protocol = "openai" | "openai-compatible" | "anthropic" | "google";
type SourceProvider = {
  id?: string;
  name?: string;
  npm?: string;
  api?: string;
  doc?: string;
};

const packageProtocols: Record<string, Protocol> = {
  "@ai-sdk/openai": "openai",
  "@ai-sdk/openai-compatible": "openai-compatible",
  "@ai-sdk/anthropic": "anthropic",
  "@ai-sdk/google": "google",
};

const officialBaseUrls: Record<string, string> = {
  openai: "https://api.openai.com/v1",
  anthropic: "https://api.anthropic.com/v1",
  google: "https://generativelanguage.googleapis.com/v1beta",
};

function quote(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

async function main() {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) throw new Error(`models.dev returned HTTP ${response.status}`);
  const source = await response.json() as Record<string, SourceProvider>;
  const presets = Object.entries(source).flatMap(([sourceId, provider]) => {
    const protocol = provider.npm ? packageProtocols[provider.npm] : undefined;
    if (!protocol) return [];
    const id = provider.id || sourceId;
    const baseUrl = provider.api || officialBaseUrls[id];
    if (!baseUrl) return [];
    return [{
      id: `models-dev:${id}`,
      name: provider.name || id,
      protocol,
      baseUrl,
      docsUrl: provider.doc || null,
      logoId: id,
    }];
  }).sort((a, b) => a.name.localeCompare(b.name));

  presets.push({
    id: "custom-openai-compatible",
    name: "Custom OpenAI Compatible",
    protocol: "openai-compatible",
    baseUrl: "",
    docsUrl: null,
    logoId: "openai-compatible",
  });

  const body = `/**\n * Generated by pnpm ai:presets:update from ${SOURCE_URL}.\n * Source: sst/models.dev (MIT); see docs/licenses/models.dev-MIT.md.\n */\n\n` +
    `export const API_PRESET_SNAPSHOT = ${quote({
      source: SOURCE_URL,
      generatedAt: new Date().toISOString(),
      presets,
    })} as const;\n`;
  await writeFile(OUTPUT, body, "utf8");
  console.log(`Wrote ${presets.length} API presets to ${OUTPUT}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : "Preset update failed");
  process.exitCode = 1;
});
